// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using msvHarmony.Infrastructure.DataSource;

#nullable disable

namespace msvHarmony.Infrastructure.Migrations
{
    [DbContext(typeof(HarmonyContext))]
    [Migration("20240402203309_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("msvHarmony.Domain.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Anio")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiscograficaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeneroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Portada")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("DiscograficaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Album", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddf3f3e-c737-4d93-81bf-2a15354ceee7"),
                            Anio = 1982,
                            ArtistaId = new Guid("b2d8a25a-01b3-454a-bb62-c829cff931b7"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(1737),
                            DiscograficaId = new Guid("7e49603a-44e5-48d3-990c-691008b0e88a"),
                            GeneroId = new Guid("8fed34da-dbe0-4ffb-b7e4-59b1546d446e"),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(1754),
                            Portada = "Thriller.jpg",
                            Titulo = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("a9cbd226-1b7b-4efe-b5d1-b2951bf16d39"),
                            Anio = 2020,
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(1764),
                            DiscograficaId = new Guid("7e49603a-44e5-48d3-990c-691008b0e88a"),
                            GeneroId = new Guid("c0fa37f3-5fb3-41d2-ba70-05fcbd352218"),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(1765),
                            Portada = "UltimoTour.jpg",
                            Titulo = "El Último Tour del Mundo"
                        },
                        new
                        {
                            Id = new Guid("09f84863-c6bd-4d04-a076-a145847496c8"),
                            Anio = 2019,
                            ArtistaId = new Guid("286f574b-b842-4930-86c1-b873350a0d98"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(1773),
                            DiscograficaId = new Guid("7e49603a-44e5-48d3-990c-691008b0e88a"),
                            GeneroId = new Guid("c0fa37f3-5fb3-41d2-ba70-05fcbd352218"),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(1774),
                            Portada = "Oasis.jpg",
                            Titulo = "Oasis"
                        },
                        new
                        {
                            Id = new Guid("36f0c39c-006c-4ba9-b9f1-93a0cb9c2695"),
                            Anio = 2018,
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(1782),
                            DiscograficaId = new Guid("7e49603a-44e5-48d3-990c-691008b0e88a"),
                            GeneroId = new Guid("c0fa37f3-5fb3-41d2-ba70-05fcbd352218"),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(1783),
                            Portada = "PorSiempre.jpg",
                            Titulo = "X 100pre"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Artista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Artista", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96303db8-663d-441f-b85b-f2424dc42f4c"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7233),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7242),
                            Nombre = "Beyoncé"
                        },
                        new
                        {
                            Id = new Guid("b2d8a25a-01b3-454a-bb62-c829cff931b7"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7247),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7249),
                            Nombre = "Michael Jackson"
                        },
                        new
                        {
                            Id = new Guid("c24fb9db-848c-4a9d-8ae0-44a97a38f0cb"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7253),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7254),
                            Nombre = "Bob Marley"
                        },
                        new
                        {
                            Id = new Guid("41f40298-2bce-45b5-9cf0-6017b2b12f33"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7258),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7259),
                            Nombre = "Shakira"
                        },
                        new
                        {
                            Id = new Guid("286f574b-b842-4930-86c1-b873350a0d98"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7264),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7265),
                            Nombre = "J Balvin"
                        },
                        new
                        {
                            Id = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7268),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7269),
                            Nombre = "Bad Bunny"
                        },
                        new
                        {
                            Id = new Guid("740d3805-1377-4e3e-962f-16b594401624"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7273),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7274),
                            Nombre = "Daddy Yankee"
                        },
                        new
                        {
                            Id = new Guid("839d6647-abb1-4b26-b096-626be91e8fa9"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7278),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 771, DateTimeKind.Local).AddTicks(7279),
                            Nombre = "Carlos Santana"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Cancion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Portada")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Cancion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("32b45778-764a-4ae0-9a44-5555d189d6a9"),
                            AlbumId = new Guid("dddf3f3e-c737-4d93-81bf-2a15354ceee7"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4438),
                            Duracion = 283,
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4446),
                            Nombre = "Wanna Be Startin' Somethin'",
                            Portada = "Wanna.jpg"
                        },
                        new
                        {
                            Id = new Guid("d2f3c9a1-46e5-40d6-b782-674ba61334c8"),
                            AlbumId = new Guid("dddf3f3e-c737-4d93-81bf-2a15354ceee7"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4456),
                            Duracion = 357,
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4458),
                            Nombre = "Thriller",
                            Portada = "Thriller-Cancion.jpg"
                        },
                        new
                        {
                            Id = new Guid("dbf159ea-55f1-44f5-a98e-36d45b62bc28"),
                            AlbumId = new Guid("a9cbd226-1b7b-4efe-b5d1-b2951bf16d39"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4466),
                            Duracion = 210,
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4468),
                            Nombre = "Te Mudaste",
                            Portada = "TeMudaste.jpg"
                        },
                        new
                        {
                            Id = new Guid("34645ff8-7bd8-42d6-9749-1beae05ff7ad"),
                            AlbumId = new Guid("a9cbd226-1b7b-4efe-b5d1-b2951bf16d39"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4475),
                            Duracion = 219,
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4477),
                            Nombre = "Hoy Cobré",
                            Portada = "HoyCobre.jpg"
                        },
                        new
                        {
                            Id = new Guid("9cf403ae-6c10-47aa-95ca-5dc3403ec2da"),
                            AlbumId = new Guid("09f84863-c6bd-4d04-a076-a145847496c8"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4484),
                            Duracion = 246,
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4485),
                            Nombre = "Qué Pretendes",
                            Portada = "Pretendes.jpg"
                        },
                        new
                        {
                            Id = new Guid("59bcaa11-7849-41e1-8e50-beb241e1d612"),
                            AlbumId = new Guid("09f84863-c6bd-4d04-a076-a145847496c8"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4492),
                            Duracion = 263,
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4494),
                            Nombre = "La Canción",
                            Portada = "LaCancion.jpg"
                        },
                        new
                        {
                            Id = new Guid("090e58d6-0f99-471d-a614-9401882fadcb"),
                            AlbumId = new Guid("36f0c39c-006c-4ba9-b9f1-93a0cb9c2695"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4502),
                            Duracion = 207,
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4504),
                            Nombre = "Ni Bien Ni Mal",
                            Portada = "NiBienMal.jpg"
                        },
                        new
                        {
                            Id = new Guid("d7584f4f-5b7e-4102-886c-20a59cd22752"),
                            AlbumId = new Guid("36f0c39c-006c-4ba9-b9f1-93a0cb9c2695"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4512),
                            Duracion = 214,
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 772, DateTimeKind.Local).AddTicks(4513),
                            Nombre = "Caro",
                            Portada = "Caro.jpg"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Colaboracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CancionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CancionId");

                    b.ToTable("Colaboracion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("987efd68-63f7-4b3a-a029-3c57d65126a8"),
                            ArtistaId = new Guid("b2d8a25a-01b3-454a-bb62-c829cff931b7"),
                            CancionId = new Guid("32b45778-764a-4ae0-9a44-5555d189d6a9"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1152),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1160)
                        },
                        new
                        {
                            Id = new Guid("1108f4ae-0bd1-46e3-a3d0-78f488ebd0e0"),
                            ArtistaId = new Guid("b2d8a25a-01b3-454a-bb62-c829cff931b7"),
                            CancionId = new Guid("d2f3c9a1-46e5-40d6-b782-674ba61334c8"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1168),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1169)
                        },
                        new
                        {
                            Id = new Guid("05775810-99c0-4c9f-9c64-67b62a757009"),
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CancionId = new Guid("dbf159ea-55f1-44f5-a98e-36d45b62bc28"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1175),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1176)
                        },
                        new
                        {
                            Id = new Guid("fba9d159-8866-4458-a1b3-5828af05fd40"),
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CancionId = new Guid("34645ff8-7bd8-42d6-9749-1beae05ff7ad"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1183),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1184)
                        },
                        new
                        {
                            Id = new Guid("1f4098c0-8e99-4e57-9786-5e58a0832398"),
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CancionId = new Guid("9cf403ae-6c10-47aa-95ca-5dc3403ec2da"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1189),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1190)
                        },
                        new
                        {
                            Id = new Guid("d1cc1ed8-0474-44d7-91a5-219f4325171e"),
                            ArtistaId = new Guid("286f574b-b842-4930-86c1-b873350a0d98"),
                            CancionId = new Guid("9cf403ae-6c10-47aa-95ca-5dc3403ec2da"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1196),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1197)
                        },
                        new
                        {
                            Id = new Guid("5601e689-455c-492d-8ec5-55b950101d56"),
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CancionId = new Guid("090e58d6-0f99-471d-a614-9401882fadcb"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1202),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1203)
                        },
                        new
                        {
                            Id = new Guid("e25b2548-6d17-4f83-a58e-608278bc1801"),
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CancionId = new Guid("d7584f4f-5b7e-4102-886c-20a59cd22752"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1209),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(1210)
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Discografica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Discografica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e49603a-44e5-48d3-990c-691008b0e88a"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(5344),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(5351),
                            Nombre = "Sony Music Entertainment"
                        },
                        new
                        {
                            Id = new Guid("71f1d39b-5fbd-42d7-b4df-a904880b904d"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(5356),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(5357),
                            Nombre = "Universal Music Group"
                        },
                        new
                        {
                            Id = new Guid("34a47160-6312-4f1f-a220-4608acb7daac"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(5361),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(5362),
                            Nombre = "Warner Music Group"
                        },
                        new
                        {
                            Id = new Guid("315721f0-9942-4ca2-a7cb-af423dac1d20"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(5366),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 773, DateTimeKind.Local).AddTicks(5367),
                            Nombre = "EMI Music"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Favorito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CancionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CancionId");

                    b.ToTable("Favorito", (string)null);
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Genero", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdc4a9d0-9618-413c-b8ef-3c75b2f87aa4"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6227),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6235),
                            Nombre = "Pop"
                        },
                        new
                        {
                            Id = new Guid("8fed34da-dbe0-4ffb-b7e4-59b1546d446e"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6241),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6242),
                            Nombre = "Rock"
                        },
                        new
                        {
                            Id = new Guid("005ec1d9-e027-4000-bf14-007b1dd5a1a4"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6246),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6247),
                            Nombre = "Hip-Hop/Rap"
                        },
                        new
                        {
                            Id = new Guid("b0b3b676-2509-4557-93f3-91d5c134f404"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6250),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6252),
                            Nombre = "R&B/Soul"
                        },
                        new
                        {
                            Id = new Guid("b2a94699-9ff0-4e2c-a867-4e915aa86d3a"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6255),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6256),
                            Nombre = "Jazz"
                        },
                        new
                        {
                            Id = new Guid("0a2cee36-6643-43b3-b0a3-ae29aa36ebb6"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6260),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6261),
                            Nombre = "Reggae"
                        },
                        new
                        {
                            Id = new Guid("1fe91b74-2e0a-44aa-9229-8c12d985eda9"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6266),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6267),
                            Nombre = "Country"
                        },
                        new
                        {
                            Id = new Guid("8eecad94-b361-45fa-80e5-e11a424f9388"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6271),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6272),
                            Nombre = "Electronic/Dance"
                        },
                        new
                        {
                            Id = new Guid("4eb68ff4-7b9c-4618-b64b-a91f51c4bb25"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6276),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6277),
                            Nombre = "Folk"
                        },
                        new
                        {
                            Id = new Guid("baa5cc89-28d4-4ce0-8210-24b1ec453fdf"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6280),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6282),
                            Nombre = "Blues"
                        },
                        new
                        {
                            Id = new Guid("d9df4cc3-7d0d-45ce-959b-7fb34aac6d58"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6285),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6286),
                            Nombre = "Indie"
                        },
                        new
                        {
                            Id = new Guid("541dfa54-35fc-4a70-8aae-cb7b88912945"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6290),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6291),
                            Nombre = "Metal"
                        },
                        new
                        {
                            Id = new Guid("ecb3ea6f-e1db-497a-b777-b58bf7f4f77f"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6295),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6296),
                            Nombre = "Funk"
                        },
                        new
                        {
                            Id = new Guid("c0fa37f3-5fb3-41d2-ba70-05fcbd352218"),
                            CreatedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6299),
                            LastModifiedOn = new DateTime(2024, 4, 2, 15, 33, 8, 774, DateTimeKind.Local).AddTicks(6300),
                            Nombre = "Reggaetón"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Playlist", (string)null);
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.PlaylistDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CancionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CancionId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("PlaylistDetalle", (string)null);
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Album", b =>
                {
                    b.HasOne("msvHarmony.Domain.Models.Artista", "Artista")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Album_Artista");

                    b.HasOne("msvHarmony.Domain.Models.Discografica", "Discografica")
                        .WithMany("Albums")
                        .HasForeignKey("DiscograficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Album_Discografica");

                    b.HasOne("msvHarmony.Domain.Models.Genero", "Genero")
                        .WithMany("Albums")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Album_Genero");

                    b.Navigation("Artista");

                    b.Navigation("Discografica");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Cancion", b =>
                {
                    b.HasOne("msvHarmony.Domain.Models.Album", "Album")
                        .WithMany("Cancions")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("FK_Cancion_Album");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Colaboracion", b =>
                {
                    b.HasOne("msvHarmony.Domain.Models.Cancion", "Cancion")
                        .WithMany("Colaboracions")
                        .HasForeignKey("CancionId")
                        .IsRequired()
                        .HasConstraintName("FK_Colaboracion_Cancion");

                    b.Navigation("Cancion");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Favorito", b =>
                {
                    b.HasOne("msvHarmony.Domain.Models.Cancion", "Cancion")
                        .WithMany("Favoritos")
                        .HasForeignKey("CancionId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorito_Cancion");

                    b.Navigation("Cancion");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.PlaylistDetalle", b =>
                {
                    b.HasOne("msvHarmony.Domain.Models.Cancion", "Cancion")
                        .WithMany("PlaylistDetalles")
                        .HasForeignKey("CancionId")
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistDetalle_Cancion");

                    b.HasOne("msvHarmony.Domain.Models.Playlist", "Playlist")
                        .WithMany("PlaylistDetalles")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistDetalle_Playlist");

                    b.Navigation("Cancion");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Album", b =>
                {
                    b.Navigation("Cancions");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Artista", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Cancion", b =>
                {
                    b.Navigation("Colaboracions");

                    b.Navigation("Favoritos");

                    b.Navigation("PlaylistDetalles");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Discografica", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Genero", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("msvHarmony.Domain.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
