// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using msvHarmony.Infrastructure.DataSource;

#nullable disable

namespace msvHarmony.Infrastructure.Migrations
{
    [DbContext(typeof(HarmonyContext))]
    [Migration("20240412183320_SeModificaCancioness")]
    partial class SeModificaCancioness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("msvHarmony.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Anio")
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiscograficaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeneroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Portada")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.HasIndex("DiscograficaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Album", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddf3f3e-c737-4d93-81bf-2a15354ceee7"),
                            Anio = 1982,
                            ArtistaId = new Guid("b2d8a25a-01b3-454a-bb62-c829cff931b7"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(146),
                            DiscograficaId = new Guid("7e49603a-44e5-48d3-990c-691008b0e88a"),
                            GeneroId = new Guid("8fed34da-dbe0-4ffb-b7e4-59b1546d446e"),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(163),
                            Portada = "Thriller.jpg",
                            Titulo = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("2d45f863-ce4d-4671-a75f-78e978ccb7ca"),
                            Anio = 1977,
                            ArtistaId = new Guid("c24fb9db-848c-4a9d-8ae0-44a97a38f0cb"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(173),
                            DiscograficaId = new Guid("7e49603a-44e5-48d3-990c-691008b0e88a"),
                            GeneroId = new Guid("0a2cee36-6643-43b3-b0a3-ae29aa36ebb6"),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(174),
                            Portada = "Exodus.jpg",
                            Titulo = "Exodus"
                        },
                        new
                        {
                            Id = new Guid("a9cbd226-1b7b-4efe-b5d1-b2951bf16d39"),
                            Anio = 2020,
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(256),
                            DiscograficaId = new Guid("71f1d39b-5fbd-42d7-b4df-a904880b904d"),
                            GeneroId = new Guid("c0fa37f3-5fb3-41d2-ba70-05fcbd352218"),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(257),
                            Portada = "UltimoTour.jpg",
                            Titulo = "El Último Tour del Mundo"
                        },
                        new
                        {
                            Id = new Guid("09f84863-c6bd-4d04-a076-a145847496c8"),
                            Anio = 2019,
                            ArtistaId = new Guid("286f574b-b842-4930-86c1-b873350a0d98"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(265),
                            DiscograficaId = new Guid("315721f0-9942-4ca2-a7cb-af423dac1d20"),
                            GeneroId = new Guid("c0fa37f3-5fb3-41d2-ba70-05fcbd352218"),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(266),
                            Portada = "Oasis.jpg",
                            Titulo = "Oasis"
                        },
                        new
                        {
                            Id = new Guid("36f0c39c-006c-4ba9-b9f1-93a0cb9c2695"),
                            Anio = 2018,
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(273),
                            DiscograficaId = new Guid("34a47160-6312-4f1f-a220-4608acb7daac"),
                            GeneroId = new Guid("c0fa37f3-5fb3-41d2-ba70-05fcbd352218"),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(274),
                            Portada = "PorSiempre.jpg",
                            Titulo = "X 100pre"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Artista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Artista", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96303db8-663d-441f-b85b-f2424dc42f4c"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5650),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5660),
                            Nombre = "Beyoncé"
                        },
                        new
                        {
                            Id = new Guid("b2d8a25a-01b3-454a-bb62-c829cff931b7"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5665),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5666),
                            Nombre = "Michael Jackson"
                        },
                        new
                        {
                            Id = new Guid("c24fb9db-848c-4a9d-8ae0-44a97a38f0cb"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5670),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5671),
                            Nombre = "Bob Marley"
                        },
                        new
                        {
                            Id = new Guid("41f40298-2bce-45b5-9cf0-6017b2b12f33"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5675),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5676),
                            Nombre = "Shakira"
                        },
                        new
                        {
                            Id = new Guid("286f574b-b842-4930-86c1-b873350a0d98"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5679),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5681),
                            Nombre = "J Balvin"
                        },
                        new
                        {
                            Id = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5765),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5766),
                            Nombre = "Bad Bunny"
                        },
                        new
                        {
                            Id = new Guid("740d3805-1377-4e3e-962f-16b594401624"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5771),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5772),
                            Nombre = "Daddy Yankee"
                        },
                        new
                        {
                            Id = new Guid("839d6647-abb1-4b26-b096-626be91e8fa9"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5775),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 843, DateTimeKind.Local).AddTicks(5776),
                            Nombre = "Carlos Santana"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Cancion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Portada")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Cancion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2f3c9a1-46e5-40d6-b782-674ba61334c8"),
                            AlbumId = new Guid("dddf3f3e-c737-4d93-81bf-2a15354ceee7"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3023),
                            Duracion = 357,
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3032),
                            Nombre = "Thriller",
                            Portada = "Thriller-Cancion.jpg",
                            Source = "thriller.mp3"
                        },
                        new
                        {
                            Id = new Guid("dbf159ea-55f1-44f5-a98e-36d45b62bc28"),
                            AlbumId = new Guid("a9cbd226-1b7b-4efe-b5d1-b2951bf16d39"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3040),
                            Duracion = 210,
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3041),
                            Nombre = "Te Mudaste",
                            Portada = "TeMudaste.jpg",
                            Source = "te-mudaste.mp3"
                        },
                        new
                        {
                            Id = new Guid("59bcaa11-7849-41e1-8e50-beb241e1d612"),
                            AlbumId = new Guid("09f84863-c6bd-4d04-a076-a145847496c8"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3049),
                            Duracion = 263,
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3050),
                            Nombre = "La Canción",
                            Portada = "LaCancion.jpg",
                            Source = "la-cancion.mp3"
                        },
                        new
                        {
                            Id = new Guid("090e58d6-0f99-471d-a614-9401882fadcb"),
                            AlbumId = new Guid("36f0c39c-006c-4ba9-b9f1-93a0cb9c2695"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3058),
                            Duracion = 207,
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3059),
                            Nombre = "Ni Bien Ni Mal",
                            Portada = "NiBienMal.jpg",
                            Source = "niBienMal.mp3"
                        },
                        new
                        {
                            Id = new Guid("30eb8630-4ab5-4a04-a9f8-ed6eeb622da7"),
                            AlbumId = new Guid("2d45f863-ce4d-4671-a75f-78e978ccb7ca"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3067),
                            Duracion = 207,
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(3068),
                            Nombre = "Natural Mystic",
                            Portada = "Natural-Mystic.jpg",
                            Source = "natural-mystic.mp3"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Colaboracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CancionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CancionId");

                    b.ToTable("Colaboracion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1108f4ae-0bd1-46e3-a3d0-78f488ebd0e0"),
                            ArtistaId = new Guid("b2d8a25a-01b3-454a-bb62-c829cff931b7"),
                            CancionId = new Guid("d2f3c9a1-46e5-40d6-b782-674ba61334c8"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9520),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9528)
                        },
                        new
                        {
                            Id = new Guid("05775810-99c0-4c9f-9c64-67b62a757009"),
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CancionId = new Guid("dbf159ea-55f1-44f5-a98e-36d45b62bc28"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9535),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9536)
                        },
                        new
                        {
                            Id = new Guid("5601e689-455c-492d-8ec5-55b950101d56"),
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CancionId = new Guid("090e58d6-0f99-471d-a614-9401882fadcb"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9543),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9544)
                        },
                        new
                        {
                            Id = new Guid("cfc16fef-a973-4748-b5ac-ca2cdfd2bf0b"),
                            ArtistaId = new Guid("00da8580-99e6-4e16-8a0b-d8739b4f98ff"),
                            CancionId = new Guid("59bcaa11-7849-41e1-8e50-beb241e1d612"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9549),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9550)
                        },
                        new
                        {
                            Id = new Guid("bae3e15f-dcd3-439a-bd36-332c4a6841cc"),
                            ArtistaId = new Guid("286f574b-b842-4930-86c1-b873350a0d98"),
                            CancionId = new Guid("59bcaa11-7849-41e1-8e50-beb241e1d612"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9555),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9556)
                        },
                        new
                        {
                            Id = new Guid("c7c25b3f-0cad-4e5a-a096-be6534aead82"),
                            ArtistaId = new Guid("c24fb9db-848c-4a9d-8ae0-44a97a38f0cb"),
                            CancionId = new Guid("30eb8630-4ab5-4a04-a9f8-ed6eeb622da7"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9562),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 844, DateTimeKind.Local).AddTicks(9563)
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Discografica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Discografica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e49603a-44e5-48d3-990c-691008b0e88a"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 845, DateTimeKind.Local).AddTicks(3716),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 845, DateTimeKind.Local).AddTicks(3724),
                            Nombre = "Sony Music Entertainment"
                        },
                        new
                        {
                            Id = new Guid("71f1d39b-5fbd-42d7-b4df-a904880b904d"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 845, DateTimeKind.Local).AddTicks(3728),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 845, DateTimeKind.Local).AddTicks(3729),
                            Nombre = "Universal Music Group"
                        },
                        new
                        {
                            Id = new Guid("34a47160-6312-4f1f-a220-4608acb7daac"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 845, DateTimeKind.Local).AddTicks(3733),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 845, DateTimeKind.Local).AddTicks(3734),
                            Nombre = "Warner Music Group"
                        },
                        new
                        {
                            Id = new Guid("315721f0-9942-4ca2-a7cb-af423dac1d20"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 845, DateTimeKind.Local).AddTicks(3737),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 845, DateTimeKind.Local).AddTicks(3738),
                            Nombre = "EMI Music"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Favorito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CancionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CancionId");

                    b.ToTable("Favorito", (string)null);
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Genero", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdc4a9d0-9618-413c-b8ef-3c75b2f87aa4"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5447),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5456),
                            Nombre = "Pop"
                        },
                        new
                        {
                            Id = new Guid("8fed34da-dbe0-4ffb-b7e4-59b1546d446e"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5461),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5462),
                            Nombre = "Rock"
                        },
                        new
                        {
                            Id = new Guid("005ec1d9-e027-4000-bf14-007b1dd5a1a4"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5466),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5467),
                            Nombre = "Hip-Hop/Rap"
                        },
                        new
                        {
                            Id = new Guid("b0b3b676-2509-4557-93f3-91d5c134f404"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5471),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5472),
                            Nombre = "R&B/Soul"
                        },
                        new
                        {
                            Id = new Guid("b2a94699-9ff0-4e2c-a867-4e915aa86d3a"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5476),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5477),
                            Nombre = "Jazz"
                        },
                        new
                        {
                            Id = new Guid("0a2cee36-6643-43b3-b0a3-ae29aa36ebb6"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5481),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5482),
                            Nombre = "Reggae"
                        },
                        new
                        {
                            Id = new Guid("1fe91b74-2e0a-44aa-9229-8c12d985eda9"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5485),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5486),
                            Nombre = "Country"
                        },
                        new
                        {
                            Id = new Guid("8eecad94-b361-45fa-80e5-e11a424f9388"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5489),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5491),
                            Nombre = "Electronic/Dance"
                        },
                        new
                        {
                            Id = new Guid("4eb68ff4-7b9c-4618-b64b-a91f51c4bb25"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5494),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5495),
                            Nombre = "Folk"
                        },
                        new
                        {
                            Id = new Guid("baa5cc89-28d4-4ce0-8210-24b1ec453fdf"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5498),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5499),
                            Nombre = "Blues"
                        },
                        new
                        {
                            Id = new Guid("d9df4cc3-7d0d-45ce-959b-7fb34aac6d58"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5502),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5503),
                            Nombre = "Indie"
                        },
                        new
                        {
                            Id = new Guid("541dfa54-35fc-4a70-8aae-cb7b88912945"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5507),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5508),
                            Nombre = "Metal"
                        },
                        new
                        {
                            Id = new Guid("ecb3ea6f-e1db-497a-b777-b58bf7f4f77f"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5511),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5512),
                            Nombre = "Funk"
                        },
                        new
                        {
                            Id = new Guid("c0fa37f3-5fb3-41d2-ba70-05fcbd352218"),
                            CreatedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5516),
                            LastModifiedOn = new DateTime(2024, 4, 12, 13, 33, 19, 846, DateTimeKind.Local).AddTicks(5517),
                            Nombre = "Reggaetón"
                        });
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Playlist", (string)null);
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.PlaylistDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CancionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CancionId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("PlaylistDetalle", (string)null);
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Album", b =>
                {
                    b.HasOne("msvHarmony.Domain.Entities.Artista", "Artista")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Album_Artista");

                    b.HasOne("msvHarmony.Domain.Entities.Discografica", "Discografica")
                        .WithMany("Albums")
                        .HasForeignKey("DiscograficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Album_Discografica");

                    b.HasOne("msvHarmony.Domain.Entities.Genero", "Genero")
                        .WithMany("Albums")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Album_Genero");

                    b.Navigation("Artista");

                    b.Navigation("Discografica");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Cancion", b =>
                {
                    b.HasOne("msvHarmony.Domain.Entities.Album", "Album")
                        .WithMany("Cancions")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("FK_Cancion_Album");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Colaboracion", b =>
                {
                    b.HasOne("msvHarmony.Domain.Entities.Cancion", "Cancion")
                        .WithMany("Colaboracions")
                        .HasForeignKey("CancionId")
                        .IsRequired()
                        .HasConstraintName("FK_Colaboracion_Cancion");

                    b.Navigation("Cancion");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Favorito", b =>
                {
                    b.HasOne("msvHarmony.Domain.Entities.Cancion", "Cancion")
                        .WithMany("Favoritos")
                        .HasForeignKey("CancionId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorito_Cancion");

                    b.Navigation("Cancion");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.PlaylistDetalle", b =>
                {
                    b.HasOne("msvHarmony.Domain.Entities.Cancion", "Cancion")
                        .WithMany("PlaylistDetalles")
                        .HasForeignKey("CancionId")
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistDetalle_Cancion");

                    b.HasOne("msvHarmony.Domain.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistDetalles")
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("FK_PlaylistDetalle_Playlist");

                    b.Navigation("Cancion");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Album", b =>
                {
                    b.Navigation("Cancions");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Artista", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Cancion", b =>
                {
                    b.Navigation("Colaboracions");

                    b.Navigation("Favoritos");

                    b.Navigation("PlaylistDetalles");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Discografica", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Genero", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("msvHarmony.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
